id: infoworld_idc_application_development_16_percent_quote
quote: >-
  Application development accounted for 16% of developers’ time in 2024, up from 15% the year before, while the majority
  of developers’ time was spent on operational and supportive tasks, according to the report.
source_id: infoworld_idc_developers_spend_most_time_not_coding
